export const CURRENCY = "JMD"

export const EXPENSE_CATEGORIES = [
  "Food & Dining",
  "Transportation",
  "Entertainment",
  "Utilities",
  "Health & Fitness",
  "Shopping",
  "Healthcare",
]

export const dummyExpenses = [
  {
    id: 1,
    date: "2024-06-15",
    description: "Grocery Store",
    category: "Food & Dining",
    amount: 2450,
    status: "completed",
  },
  {
    id: 2,
    date: "2024-06-14",
    description: "Gas Station",
    category: "Transportation",
    amount: 3200,
    status: "completed",
  },
  {
    id: 3,
    date: "2024-06-13",
    description: "Netflix Subscription",
    category: "Entertainment",
    amount: 1200,
    status: "completed",
  },
  {
    id: 4,
    date: "2024-06-12",
    description: "Electricity Bill",
    category: "Utilities",
    amount: 8900,
    status: "completed",
  },
  {
    id: 5,
    date: "2024-06-11",
    description: "Restaurant Dinner",
    category: "Food & Dining",
    amount: 4500,
    status: "completed",
  },
  {
    id: 6,
    date: "2024-06-10",
    description: "Gym Membership",
    category: "Health & Fitness",
    amount: 3500,
    status: "completed",
  },
  {
    id: 7,
    date: "2024-06-09",
    description: "Shopping Mall",
    category: "Shopping",
    amount: 2100,
    status: "completed",
  },
  {
    id: 8,
    date: "2024-06-08",
    description: "Water Bill",
    category: "Utilities",
    amount: 3500,
    status: "completed",
  },
  {
    id: 9,
    date: "2024-06-07",
    description: "Movie Tickets",
    category: "Entertainment",
    amount: 1200,
    status: "completed",
  },
  {
    id: 10,
    date: "2024-06-06",
    description: "Pharmacy",
    category: "Healthcare",
    amount: 1850,
    status: "completed",
  },
]

export const dummyAutomatedPayments = [
  {
    id: 1,
    name: "Water Bill",
    provider: "National Water Commission",
    amount: 3500,
    dueDate: "2024-03-18",
    status: "upcoming",
    category: "Utilities & Bills",
    lastDetected: "2 days ago",
    emailSubject: "Your NWC Bill is Ready",
    frequency: "Monthly",
    nextPaymentDate: "2024-03-18",
  },
  {
    id: 2,
    name: "Electricity Bill",
    provider: "Jamaica Public Service",
    amount: 8900,
    dueDate: "2024-03-22",
    status: "upcoming",
    category: "Utilities & Bills",
    lastDetected: "5 days ago",
    emailSubject: "JPS Bill Statement - March 2024",
    frequency: "Monthly",
    nextPaymentDate: "2024-03-22",
  },
  {
    id: 3,
    name: "Internet Service",
    provider: "Flow Jamaica",
    amount: 6500,
    dueDate: "2024-03-25",
    status: "scheduled",
    category: "Utilities & Bills",
    lastDetected: "1 week ago",
    emailSubject: "Flow Monthly Bill",
    frequency: "Monthly",
    nextPaymentDate: "2024-03-25",
  },
  {
    id: 4,
    name: "Netflix Subscription",
    provider: "Netflix",
    amount: 1200,
    dueDate: "2024-03-15",
    status: "paid",
    category: "Personal & Entertainment",
    lastDetected: "3 days ago",
    emailSubject: "Netflix - Payment Confirmation",
    frequency: "Monthly",
    nextPaymentDate: "2024-04-15",
  },
  {
    id: 5,
    name: "Gym Membership",
    provider: "FitZone Gym",
    amount: 3500,
    dueDate: "2024-03-20",
    status: "scheduled",
    category: "Health & Fitness",
    lastDetected: "1 week ago",
    emailSubject: "FitZone Monthly Membership",
    frequency: "Monthly",
    nextPaymentDate: "2024-03-20",
  },
]

export const dummyCategoryData = [
  { category: "Food & Dining", amount: 6950 },
  { category: "Transportation", amount: 3200 },
  { category: "Entertainment", amount: 1200 },
  { category: "Utilities", amount: 8900 },
  { category: "Health & Fitness", amount: 3500 },
  { category: "Shopping", amount: 2100 },
]

export const dummyMonthlyData = [
  { month: "Jan", expenses: 18500 },
  { month: "Feb", expenses: 21200 },
  { month: "Mar", expenses: 19800 },
  { month: "Apr", expenses: 23400 },
  { month: "May", expenses: 20100 },
  { month: "Jun", expenses: 25850 },
]

export const dummyStats = {
  totalBalance: 45230.5,
  monthlyExpenses: 18450,
  budgetRemaining: 6550,
  savingsGoal: 12340,
}
